apiVersion: apps/v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: prometheus
    name: prometheus
  spec:
    ports:
    - name: "9090"
      port: 9090
      targetPort: 9090
    selector:
      app: prometheus
  status:
    loadBalancer: {}
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: prometheus
    name: prometheus
  spec:
    selector:
      matchLabels:
        app: prometheus
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: prometheus
      spec:
        containers:
        - image: prom/prometheus:latest
          name: capi-prometheus
          ports:
          - containerPort: 9090
          resources: {}
          volumeMounts:
          - name: prometheus-config
            mountPath: /etc/prometheus/prometheus.yml
            subPath: prometheus.yml
        restartPolicy: Always
        volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
  status: {}
kind: List
metadata: {}
